dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - g++

script:
  - git clone https://github.com/danmar/cppcheck.git
  - ls
  - cd cppcheck
  - ls
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
