dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - g++

script:
  - cd static
  - gcc -c Static.c -std=c99 -o Static.o
  - ar rc libStatic.a Static.o
  - rm Static.o
  - cd ../dynamic
  - gcc -c -Wall -Werror -std=c99 -fpic Dynamic.c
  - gcc -shared -o libDynamic.so Dynamic.o
  - rm Dynamic.o
  - cd ..
  - cmake CMakeLists.txt
  - make
  - ./unit_tests
