dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - g++

script:
  - sudo apt update
  - sudo apt install valgrind
  - g++ main.c Polygon_calculator.cpp -o Calculator
  - cmake CMakeLists.txt
  - make
  - ./unit_tests
  - valgrind --tool=memcheck ./unit_tests

