dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
  - g++

script:
  - sudo apt update
  - sudo apt install valgrind
  - cmake CMakeLists.txt
  - make
  - ls
  - ./unit_tests
  - valgrind ./unit_tests
